### ISSUE TITLE
Unable to Build on Node 12.13.1 (Node-GYP)

### ISSUE THREAD

**Issue by mkellsy** [macnow/homebridge-platform-orvibo#11]
This plugin can not be installed on systems running Node 12.13.1 (Current LTS).

I can confirm that node-gyp is configured properly and working on my system(s), we use it for many projects.

I have tested this on
1. macOs Catilina
2. Fedora 31
3. Debian 10/Raspbian (x86_64, arm6l and arm7l)

This is the Node-GYP errors we are getting
```
> sleep@3.0.1 install /Users/mkellsy/.hoobs/node_modules/sleep
> node-gyp rebuild
  CXX(target) Release/obj.target/node_sleep/sleep.o
../sleep.cc:6:11: error: no member named 'Handle' in namespace 'v8'
using v8::Handle;
      ~~~~^
../sleep.cc:42:30: error: too few arguments to function call, single argument 'context' was not specified
  sleep(info[0]->Uint32Value());
        ~~~~~~~~~~~~~~~~~~~~ ^
/Users/mkellsy/Library/Caches/node-gyp/12.13.1/include/node/v8.h:2611:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/mkellsy/Library/Caches/node-gyp/12.13.1/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../sleep.cc:54:31: error: too few arguments to function call, single argument 'context' was not specified
  usleep(info[0]->Uint32Value());
         ~~~~~~~~~~~~~~~~~~~~ ^
/Users/mkellsy/Library/Caches/node-gyp/12.13.1/include/node/v8.h:2611:3: note: 'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/mkellsy/Library/Caches/node-gyp/12.13.1/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../sleep.cc:62:52: error: too few arguments to function call, single argument 'context' was not specified
    Nan::New<FunctionTemplate>(Sleep)->GetFunction());
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/mkellsy/Library/Caches/node-gyp/12.13.1/include/node/v8.h:5995:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/mkellsy/Library/Caches/node-gyp/12.13.1/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../sleep.cc:64:53: error: too few arguments to function call, single argument 'context' was not specified
    Nan::New<FunctionTemplate>(USleep)->GetFunction());
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/mkellsy/Library/Caches/node-gyp/12.13.1/include/node/v8.h:5995:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/mkellsy/Library/Caches/node-gyp/12.13.1/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
5 errors generated.
make: *** [Release/obj.target/node_sleep/sleep.o] Error 1
gyp
 ERR!
 build error
gyp
 ERR! stack Error: `make` failed with exit code: 2
gyp ERR!
stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp
 ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mkellsy/.hoobs/node_modules/sleep
gyp
 ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm
ERR! code ELIFECYCLE
npm ERR! errno 1
npm

ERR! sleep@3.0.1 install: `node-gyp rebuild`
npm ERR!
 Exit status 1
npm ERR! 
npm ERR!
 Failed at the sleep@3.0.1 install script.
npm
ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm
 ERR! A complete log of this run can be found in:
npm ERR!     /Users/mkellsy/.npm/_logs/2019-12-18T18_11_48_490Z-debug.log
```
[2019-12-18T18_11_48_490Z-debug.log](https://github.com/macnow/homebridge-platform-orvibo/files/3979895/2019-12-18T18_11_48_490Z-debug.log)

**Comment by random9133** [comment]
Looks similar to this problem, which I found a solution for, might work in your case [https://github.com/macnow/homebridge-platform-orvibo/issues/10#issuecomment-576045938](url)
